[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "spirals_csc"
version = "0.0.1"
dependencies = [
    "PyQt6",
    'python_version>=3.8',
]

[tool.setuptools.packages]
find={}